CREATE OR REPLACE PACKAGE G_PARTITION_MGMT AS

--Autor: Matias Orquera. Fecha: 21.02.2017

PROCEDURE P_TRUNCATE_PART_HOUR(P_TABLA VARCHAR2,P_FECHA_DESDE IN CHAR, P_FECHA_HASTA IN CHAR);
PROCEDURE P_TRUNCATE_PART_DAY(P_TABLA VARCHAR2,P_FECHA_DESDE IN CHAR, P_FECHA_HASTA IN CHAR);

END G_PARTITION_MGMT;

CREATE OR REPLACE PACKAGE BODY G_PARTITION_MGMT AS

--Autor: Matias Orquera. Fecha: 21.02.2017.

-- LOG --
L_ERRORS NUMBER;
L_ERRNO  NUMBER;
L_MSG    VARCHAR2(500);
  -- END LOG --

V_LINEA VARCHAR2(200);

PROCEDURE P_TRUNCATE_PART_HOUR(P_TABLA VARCHAR2,P_FECHA_DESDE IN CHAR, P_FECHA_HASTA IN CHAR)
IS

--Autor: Matias Orquera. Fecha: 18.01.2017

CURSOR FECHAS IS
SELECT TO_CHAR(DIA,'DD.MM.YYYY')||' '||HORA FECHA
FROM CALIDAD_STATUS_REFERENCES
WHERE FECHA BETWEEN TO_DATE(P_FECHA_DESDE, 'DD.MM.YYYY HH24') AND TO_DATE(P_FECHA_HASTA, 'DD.MM.YYYY HH24');

BEGIN

  FOR TR IN FECHAS LOOP

    V_LINEA := 'ALTER TABLE '||P_TABLA||' TRUNCATE PARTITION FOR(TO_DATE('''||TR.FECHA||''',''DD.MM.YYYY HH24''))';

    DBMS_OUTPUT.PUT_LINE(V_LINEA);
    EXECUTE IMMEDIATE V_LINEA;

  END LOOP;

  EXCEPTION
    WHEN OTHERS THEN
      --DBMS_OUTPUT.PUT_LINE(SQLERRM);
      L_ERRNO := SQLCODE;
      L_MSG := SQLERRM;
      G_ERROR_LOG_NEW.P_LOG_ERROR('P_TRUNCATE_PART_HOUR',L_ERRNO,L_MSG, V_LINEA);
END;

PROCEDURE P_TRUNCATE_PART_DAY(P_TABLA VARCHAR2,P_FECHA_DESDE IN CHAR, P_FECHA_HASTA IN CHAR)
IS

--Autor: Matias Orquera. Fecha: 18.01.2017

CURSOR FECHAS IS
SELECT DISTINCT TO_CHAR(DIA,'DD.MM.YYYY') FECHA
FROM CALIDAD_STATUS_REFERENCES
WHERE FECHA BETWEEN TO_DATE(P_FECHA_DESDE, 'DD.MM.YYYY') AND TO_DATE(P_FECHA_HASTA, 'DD.MM.YYYY');

BEGIN

  FOR TR IN FECHAS LOOP

    V_LINEA := 'ALTER TABLE '||P_TABLA||' TRUNCATE PARTITION FOR(TO_DATE('''||TR.FECHA||''',''DD.MM.YYYY''))';

    DBMS_OUTPUT.PUT_LINE(V_LINEA);
    EXECUTE IMMEDIATE V_LINEA;

  END LOOP;


  EXCEPTION
    WHEN OTHERS THEN
      --DBMS_OUTPUT.PUT_LINE(SQLERRM);
      L_ERRNO := SQLCODE;
      L_MSG := SQLERRM;
      G_ERROR_LOG_NEW.P_LOG_ERROR('P_TRUNCATE_PART_DAY',L_ERRNO,L_MSG, V_LINEA);
END;

END G_PARTITION_MGMT;
