CREATE TABLE CISCO_GGSN_EPDG_DAY
   (  
    FECHA                                   DATE,
    EQUIPO                                  VARCHAR2(30),
    VPNNAME                                 VARCHAR2(30),
    VPNID                                   NUMBER,
    SERVNAME                                VARCHAR2(30),
    SERVID                                  NUMBER,
    PDN_IPV4_ACTIVE                         NUMBER,
    PDN_IPV4_SETUP                          NUMBER,
    PDN_IPV4_RELEASED                       NUMBER,
    PDN_IPV6_ACTIVE                         NUMBER,
    PDN_IPV6_SETUP                          NUMBER,
    PDN_IPV6_RELEASED                       NUMBER,
    PDN_IPV4V6_ACTIVE                       NUMBER,
    PDN_IPV4V6_SETUP                        NUMBER,
    PDN_IPV4V6_RELEASED                     NUMBER,
    NUM_GTP_BEARER_MODIFIED                 NUMBER,
    NUM_GTP_DB_ACTIVE                       NUMBER,
    NUM_GTP_DB_RELEASED                     NUMBER,
    CURSESS                                 NUMBER,
    CURSES_PMIPV6_IPV4                      NUMBER,
    CURSES_PMIPV6_IPV6                      NUMBER,
    CURSES_PMIPV6_IPV4V6                    NUMBER,
    CURSES_GTP_IPV4                         NUMBER,
    TOTPMIPV6_SUCCESS                       NUMBER,
    TOTPMIPV6_FAILURE                       NUMBER,
    PGW_FALLBACK_ATTEMPTED                  NUMBER,
    PGW_FALLBACK_SUCCEEDED                  NUMBER,
    PGW_FALLBACK_FAILED                     NUMBER,
    PGW_FALLBACK_NO_ALTERNATE_PGW           NUMBER,
    TOTGTP_ATTEMPT                          NUMBER,
    TOTGTP_SUCCESS                          NUMBER,
    TOTGTP_FAILURE                          NUMBER,
    DISCONNECT_TOTAL                        NUMBER,
    DISCONNECT_LOCAL                        NUMBER,
    DISCONNECT_UE                           NUMBER,
    DISCONNECT_PGW                          NUMBER,
    DISCONNECT_REMOTE                       NUMBER,
    SESS_DCON_REMOTE                        NUMBER,
    SESS_DCON_ADMIN                         NUMBER,
    SESS_DCON_IDLE_TIMEOUT                  NUMBER,
    SESS_DCON_ABS_TIMEOUT                   NUMBER,
    SESS_DCON_LONGDUR_TIMEOUT               NUMBER,
    SESS_DCON_SESSSETUP_TIMEOUT             NUMBER,
    SESS_DCON_NORESOURCE                    NUMBER,
    SESS_DCON_AUTHFAIL                      NUMBER,
    SESS_DCON_FLOWADD_FAILURE               NUMBER,
    SESS_DCON_INVALID_DEST                  NUMBER,
    SESS_DCON_SRCADDR_VIOLATION             NUMBER,
    SESS_DCON_LMAREVOC                      NUMBER,
    SESS_DCON_DUPREQ                        NUMBER,
    SESS_DCON_ADDRASSIGN_FAILURE            NUMBER,
    SESS_DCON_HANDOFF                       NUMBER,
    SESS_DCON_MISC                          NUMBER,
    REAUTH_ATTEMPT                          NUMBER,
    REAUTH_SUCCESS                          NUMBER,
    REAUTH_FAILURE                          NUMBER,
    REAUTHOR_ATTEMPT                        NUMBER,
    REAUTHOR_SUCCESS                        NUMBER,
    REAUTHOR_FAILURE                        NUMBER,
    TXBYTES                                 NUMBER,
    TXPKTS                                  NUMBER,
    RXBYTES                                 NUMBER,
    RXPKTS                                  NUMBER,
    PKT_VIOLATION                           NUMBER,
    EAP_RXTTLSRVRPASSTHRU                   NUMBER,
    NUM_QCI1_BEARER_ACTIVE                  NUMBER,
    NUM_QCI1_BEARER_SETUP                   NUMBER,
    NUM_QCI1_BEARER_RELEASED                NUMBER,
    NUM_QCI2_BEARER_ACTIVE                  NUMBER,
    NUM_QCI2_BEARER_SETUP                   NUMBER,
    NUM_QCI2_BEARER_RELEASED                NUMBER,
    NUM_QCI3_BEARER_ACTIVE                  NUMBER,
    NUM_QCI3_BEARER_SETUP                   NUMBER,
    NUM_QCI3_BEARER_RELEASED                NUMBER,
    NUM_QCI4_BEARER_ACTIVE                  NUMBER,
    NUM_QCI4_BEARER_SETUP                   NUMBER,
    NUM_QCI4_BEARER_RELEASED                NUMBER,
    NUM_QCI5_BEARER_ACTIVE                  NUMBER,
    NUM_QCI5_BEARER_SETUP                   NUMBER,
    NUM_QCI5_BEARER_RELEASED                NUMBER,
    NUM_QCI6_BEARER_ACTIVE                  NUMBER,
    NUM_QCI6_BEARER_SETUP                   NUMBER,
    NUM_QCI6_BEARER_RELEASED                NUMBER,
    NUM_QCI7_BEARER_ACTIVE                  NUMBER,
    NUM_QCI7_BEARER_SETUP                   NUMBER,
    NUM_QCI7_BEARER_RELEASED                NUMBER,
    APN_EPDG_GTPV2_SUCCESS_RATE             NUMBER,
    TX_THROUGHPUT                           NUMBER,
    RX_THROUGHPUT                           NUMBER,
    APN_EPDG_SYS_THROUGHPUT                 NUMBER
  )
  TABLESPACE DEVELOPER 
  PARTITION BY RANGE (FECHA) INTERVAL (NUMTODSINTERVAL (1,'DAY'))  
 (
 PARTITION EPDG_GGSN_20161205  VALUES LESS THAN (TO_DATE(' 2016-12-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'))
 );
 
 ALTER TABLE CISCO_GGSN_EPDG_DAY ADD CONSTRAINT CISCO_GGSN_EPDG_DAY_PK_NEW PRIMARY KEY (FECHA, VPNID, SERVID)
USING INDEX LOCAL TABLESPACE DEVELOPER;